name: Build and Release

on:
  push:
    tags:
      - 'v*'
    branches:
      - main

permissions:
  contents: write

jobs:
  build-windows:
    runs-on: windows-latest
    if: startsWith(github.ref, 'refs/tags/')
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller
    
    - name: Build executable
      run: |
        pyinstaller --onefile --windowed --icon=app/resources/icon.ico --name="EventWizard" main.py
    
    - name: Create release archive
      run: |
        mkdir release
        copy dist\EventWizard.exe release\
        copy README.md release\
        copy LICENSE release\
        powershell Compress-Archive -Path release\* -DestinationPath EventWizard-${{ github.ref_name }}-windows.zip
    
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          EventWizard-${{ github.ref_name }}-windows.zip
          dist/EventWizard.exe
        body: |
          ## Event Wizard ${{ github.ref_name }}
          
          Windows Event log analysis tool with GUI interface.
          
          ### Installation
          1. Download `EventWizard.exe`
          2. Download EvtxECmd.exe from [Eric Zimmerman's Tools](https://ericzimmerman.github.io/#!index.md)
          3. Place both files in the same directory
          4. Run EventWizard.exe
          
          ### What's included
          - Windows executable (no Python installation required)
          - README and LICENSE files in the zip archive
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 